{"name": "Unsuccessful login", "status": "passed", "steps": [{"name": "Error message is visible", "status": "passed", "start": 1737700609497, "stop": 1737700609497}], "parameters": [{"name": "username", "value": "'standard_user'"}, {"name": "password", "value": "''"}, {"name": "driver", "value": "'Edge'"}], "start": 1737700609301, "stop": 1737700609533, "uuid": "2c32f475-f97c-4a42-8c90-e4f4b6ee9ada", "historyId": "835dedd962576e463d3e402931bc7f9f", "testCaseId": "b876685be5aab7257716ff999cc789c0", "fullName": "Tests.test_Login.TestLogin#test_1", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Login"}, {"name": "parentSuite", "value": "Tests"}, {"name": "suite", "value": "test_Login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "fv-az1120-982"}, {"name": "thread", "value": "1996-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.test_Login"}]}