{"name": "Unsuccessful login", "status": "passed", "steps": [{"name": "Error message is visible", "status": "passed", "start": 1739069037443, "stop": 1739069037443}], "parameters": [{"name": "username", "value": "'standard_user'"}, {"name": "password", "value": "''"}, {"name": "driver", "value": "'Edge'"}], "start": 1739069037249, "stop": 1739069037478, "uuid": "46a436e1-fd3f-4990-aa4a-d82bb97f88e0", "historyId": "835dedd962576e463d3e402931bc7f9f", "testCaseId": "b876685be5aab7257716ff999cc789c0", "fullName": "Tests.test_Login.TestLogin#test_1", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Login"}, {"name": "parentSuite", "value": "Tests"}, {"name": "suite", "value": "test_Login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "fv-az1334-738"}, {"name": "thread", "value": "1949-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.test_Login"}]}